/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Czar
 */
public class administraradmin extends javax.swing.JFrame {
    private JPanel adminis;
    /**
     * Creates new form administraradmin
     */
    public administraradmin() {
        initComponents();
        adminis= new JPanel();
        adminis.setLayout(new BorderLayout());
        adminis.add(new JLabel(""),BorderLayout.CENTER);
    }
    
    public JPanel getAdministrar(){
        return Administrar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administrar = new javax.swing.JPanel();
        AgregarB = new javax.swing.JToggleButton();
        ModigicarB = new javax.swing.JToggleButton();
        softvets = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 520));
        setPreferredSize(new java.awt.Dimension(620, 520));

        Administrar.setBackground(new java.awt.Color(255, 255, 255));
        Administrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarB.setBackground(new java.awt.Color(0, 204, 204));
        AgregarB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarB.setForeground(new java.awt.Color(255, 255, 255));
        AgregarB.setText("Agregar ");
        Administrar.add(AgregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 40));

        ModigicarB.setBackground(new java.awt.Color(0, 204, 204));
        ModigicarB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModigicarB.setForeground(new java.awt.Color(255, 255, 255));
        ModigicarB.setText("Modificar");
        ModigicarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModigicarBActionPerformed(evt);
            }
        });
        Administrar.add(ModigicarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 170, 40));

        softvets.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        softvets.setForeground(new java.awt.Color(153, 153, 153));
        softvets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventana/imagenlogo/2222CIRCULOS.png"))); // NOI18N
        softvets.setText("SOFTVETS");
        Administrar.add(softvets, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Administrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Administrar, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModigicarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModigicarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModigicarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administraradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administraradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administraradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administraradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administraradmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Administrar;
    private javax.swing.JToggleButton AgregarB;
    private javax.swing.JToggleButton ModigicarB;
    private javax.swing.JLabel softvets;
    // End of variables declaration//GEN-END:variables
}
