/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Czar
 */
public class gestionaradmin extends javax.swing.JFrame {
    private JPanel gestion;
    /**
     * Creates new form gestionaradmin
     */
    public gestionaradmin() {
        initComponents();
        gestion= new JPanel();
        gestion.setLayout(new BorderLayout());
        gestion.add(new JLabel(""),BorderLayout.CENTER);
    }
    public JPanel getGestion(){
        return Gestion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gestion = new javax.swing.JPanel();
        softvets = new javax.swing.JLabel();
        GestionarCYM = new javax.swing.JToggleButton();
        GestionarC = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 520));
        setPreferredSize(new java.awt.Dimension(620, 520));

        Gestion.setBackground(new java.awt.Color(255, 255, 255));
        Gestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        softvets.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        softvets.setForeground(new java.awt.Color(153, 153, 153));
        softvets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventana/imagenlogo/2222CIRCULOS.png"))); // NOI18N
        softvets.setText("SOFTVETS");
        Gestion.add(softvets, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 190, 60));

        GestionarCYM.setBackground(new java.awt.Color(0, 204, 204));
        GestionarCYM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GestionarCYM.setForeground(new java.awt.Color(255, 255, 255));
        GestionarCYM.setText("Gestionar Clientes y Mascotas");
        GestionarCYM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarCYMActionPerformed(evt);
            }
        });
        Gestion.add(GestionarCYM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        GestionarC.setBackground(new java.awt.Color(0, 204, 204));
        GestionarC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GestionarC.setForeground(new java.awt.Color(255, 255, 255));
        GestionarC.setText("Gestionar Citas");
        GestionarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarCActionPerformed(evt);
            }
        });
        Gestion.add(GestionarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Gestion, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Gestion, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionarCYMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarCYMActionPerformed
        GestionClientesPersonas go = new GestionClientesPersonas();
        go.setVisible(true);
        
    }//GEN-LAST:event_GestionarCYMActionPerformed

    private void GestionarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarCActionPerformed
        GestionCitas ga = new GestionCitas();
        
        ga.setVisible(true);
        
    }//GEN-LAST:event_GestionarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionaradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionaradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionaradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionaradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionaradmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Gestion;
    private javax.swing.JToggleButton GestionarC;
    private javax.swing.JToggleButton GestionarCYM;
    private javax.swing.JLabel softvets;
    // End of variables declaration//GEN-END:variables
}
